export const txServiceList = {
  Arbitrum: "https://safe-transaction-arbitrum.safe.global/",
  Aurora: "https://safe-transaction-aurora.safe.global/",
  Avalanche: "https://safe-transaction-avalanche.safe.global/",
  Base: "https://safe-transaction-base.safe.global/",
  BaseGoerli: "https://safe-transaction-base-testnet.safe.global/",
  BnbSmartChain: "https://safe-transaction-bsc.safe.global/",
  Celo: "https://safe-transaction-celo.safe.global/",
  EthereumMainnet: "https://safe-transaction-mainnet.safe.global/",
  GnosisChain: "https://safe-transaction-gnosis-chain.safe.global/",
  Goerli: "https://safe-transaction-goerli.safe.global/",
  Optimism: "https://safe-transaction-optimism.safe.global/",
  Polygon: "https://safe-transaction-polygon.safe.global/",
  PolygonzkEVM: "https://safe-transaction-zkevm.safe.global/",
  zkSyncEraMainnet: "https://safe-transaction-zksync.safe.global/",
};

export const ProviderLink = {
  Arbitrum: "https://arbitrum-mainnet.infura.io",
  Aurora: "https://mainnet.aurora.dev",
  Avalanche: "https://api.avax.network/ext/bc/C/rpc",
  Base: "https://mainnet.base.org/",
  BaseGoerli: "https://base-goerli.gateway.tenderly.co",
  BnbSmartChain: "https://bsc-dataseed.binance.org/",
  Celo: "https://forno.celo.org",
  EthereumMainnet: "https://mainnet.infura.io/v3/",
  GnosisChain: "https://rpc.gnosischain.com",
  Goerli: "https://rpc.ankr.com/eth_goerli",
  Optimism: "https://optimistic.ethereum.io",
  Polygon: "https://polygon-mainnet.infura.io",
  PolygonzkEVM: "https://zkevm-rpc.com",
  zkSyncEraMainnet: "https://mainnet.era.zksync.io",
};
